line_length:
- 450 # warning
- 500 # error
type_body_length:
- 450 # warning
- 550 # error
file_length:
- 450 # warning
cyclomatic_complexity:
- 12 # warning
function_body_length:
- 60 # warning
disabled_rules:
- trailing_whitespace
- force_cast
- non_optional_string_data_conversion
